In [1]:
import numpy as np, matplotlib.pyplot as plt
from itertools import combinations, product

In [40]:
def sig(F,K):
    '''
    Computes [F:K] with natural ordering, does not take into account the orientation of each simplex.
    '''
    F, K = sorted(F), sorted(K)
    if len(F) == len(K)+1 and set(F).union(set(K))==set(F):
        c = list((set(F)-set(K)))[0]
        if F.index(c) % 2 == 0:
            return 1
        else:
            return -1
    else:
        return 0
    
def coboundary(X,l):
    '''
    The l^{th} coboundar map, returns -1 if not defined. The input X is a list of lists on groud set [n].
    '''
    C = sorted([simplex for simplex in X if len(simplex)==l+1])
    R = sorted([simplex for simplex in X if len(simplex)==l+2])
    if len(C)==0 or len(R)==0 or l < -1:
        return None
    r, c = len(R), len(C)
    M = []
    for i in range(r):
        RR = []
        for j in range(c):
            #print(R[i], C[j], sig(R[i],C[j]))
            RR.append(sig(R[i],C[j]))
        M.append(RR)
    return np.array(M)

def boundary(X,l):
    M = coboundary(X,l-1)
    if M is None:
        return M
    return M.T

In [5]:
def cliques(G):
    '''
    getting a hold on the cliques of a graph
    '''
    C = set()
    max_cliques = sage.graphs.cliquer.all_cliques(G,min_size=1)
    for max_clique in max_cliques:
        for subset in power_set(max_clique):
           C.add(subset)
    return sorted(list(C))

def power_set(S):
    '''
    utility function
    '''
    power_s = set()
    for i in range(len(S)+1):
        for subset in combinations(S,i):
            power_s.add(subset)
    return power_s

In [48]:
def lu_spectrum(G,l):
    '''
    The l^{th} up-laplacian spectrum of graph G, input should be Sagemath's graph object.
    '''
    A = coboundary(cliques(G),l)
    if A is None:
        return A
    eigvals = np.around(np.linalg.eigvals(A.T.dot(A)),3)
    e, c = np.unique(eigvals,return_counts=True)
    e = [np.linalg.norm(entry) for entry in e]
    return [list(e), list(c)]
    #return eigvals

def ll_spectrum(G,l):
    '''
    See lu_spectrum() for details.
    '''
    l -= 1
    A = coboundary(cliques(G),l)
    if A is None:
        return A
    eigvals = np.around(np.linalg.eigvals(A.dot(A.T)),2)
    e, c = np.unique(eigvals,return_counts=True)
    e = [np.linalg.norm(entry) for entry in e]
    return [list(e), list(c)]
    #return eigvals

In [8]:
def TriangularGraph(n):
    '''
    Construction of triangular graph on n symbols
    '''
    s = range(1,n+1)
    G = Graph()
    for pair in combinations(s,2):
        G.add_vertex(pair)
    
    for pair in combinations(G.vertices(),2):
        v, w = pair
        if len(set(v).intersection(set(w))) == 1:
            G.add_edge(v,w)
    return G

In [52]:
#Examples

In [20]:
X = [[],[1],[2],[3],[4],[1,2],[1,3],[2,3],[2,4],[3,4],[1,2,3],[2,3,4]]

In [38]:
coboundary(X,1)

array([[ 1, -1,  1,  0,  0],
       [ 0,  0,  1, -1,  1]])

In [41]:
boundary(X,1)

array([[-1, -1,  0,  0,  0],
       [ 1,  0, -1, -1,  0],
       [ 0,  1,  1,  0, -1],
       [ 0,  0,  0,  1,  1]])

In [42]:
coboundary(X,0)

array([[-1,  1,  0,  0],
       [-1,  0,  1,  0],
       [ 0, -1,  1,  0],
       [ 0, -1,  0,  1],
       [ 0,  0, -1,  1]])

In [46]:
type(boundary(X,3))

<class 'NoneType'>

In [49]:
lu_spectrum(TriangularGraph(4),1)

[[0.0, 2.0, 4.0, 6.0], [5, 3, 3, 1]]

In [50]:
lu_spectrum(TriangularGraph(4),3)

In [54]:
## Chang graphs
# The adjacency matrices have been obtained from Mathematica

In [55]:
Chang1 = '0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 0 1 1 0 0 1 1 0 0 0 1 1 0 0 0 1 1 0 0 0 1 0 0 0 0 1 1 1 1 0 0 1 0 1 0 1 0 0 1 0 1 0 0 1 0 1 0 0 0 1 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 0 1 0 1 0 0 1 0 1 0 0 0 1 0 0 1 1 1 0 1 0 0 1 0 0 1 0 1 0 0 1 0 1 0 0 1 0 1 0 0 0 1 0 1 1 1 0 0 1 1 0 0 0 0 1 1 0 0 0 1 1 0 0 0 1 1 0 0 0 0 1 1 0 0 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 1 0 0 0 0 1 1 0 0 1 1 0 0 1 0 1 0 0 1 0 1 1 1 0 1 0 0 0 0 1 0 0 0 1 0 1 1 0 1 0 0 0 1 0 1 0 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 1 1 0 1 0 0 0 0 1 0 1 1 1 1 0 1 0 0 0 1 0 0 0 0 1 0 0 1 1 0 1 1 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 1 0 0 0 0 1 1 0 0 1 1 0 1 0 1 1 0 0 0 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 1 1 0 0 1 0 1 0 1 0 1 0 0 0 1 0 0 0 1 0 1 1 1 0 1 0 0 0 1 0 1 1 0 0 1 0 0 1 0 1 0 0 0 1 0 0 1 1 0 1 1 0 0 1 0 0 0 1 1 1 0 0 1 0 0 0 1 0 1 0 0 0 1 0 1 1 1 0 1 0 0 0 1 0 0 1 1 0 1 0 1 0 0 0 0 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 0 0 1 1 0 0 1 1 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 1 1 1 1 1 0 0 1 0 0 1 1 0 1 0 0 0 1 0 0 0 0 1 0 0 0 1 0 1 1 1 1 0 1 1 0 0 0 1 0 1 0 1 0 0 0 1 0 0 0 0 1 0 0 1 1 0 1 1 0 1 1 1 0 0 0 1 0 0 1 0 1 0 0 0 1 0 0 0 0 1 0 1 1 1 0 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1 0 0 0 0 1 1 1 1 1 0 1 0 0 1 1 0 0 0 1 0 0 0 0 1 1 0 0 1 1 1 0 0 1 1 1 0 0 1 0 0 0 1 1 0 0 0 0 1 0 0 0 1 0 1 1 0 1 0 1 1 0 1 0 1 1 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 1 1 1 0 0 1 1 1 0 0 1 1 1 0 0 1 0 1 0 0 0 0 0 0 0 1 0 0 1 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 1 1 1 0 0 1 1 1 1 0 0 0'

In [56]:
Chang2 = '0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  1 0 1 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0  1 1 0 1 1 1 1 0 1 0 0 0 0 1 0 0 0 0 1 1 1 1 0 0 0 0 0 0  1 1 1 0 1 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 1 1 1 0 0 0  1 1 1 1 0 1 0 1 0 0 1 0 0 0 0 1 0 0 1 1 0 0 1 0 0 1 0 0  1 1 1 1 1 0 0 1 0 0 0 1 0 0 0 0 1 0 1 0 1 0 0 1 0 0 1 0  1 1 1 1 0 0 0 0 1 1 0 0 1 1 1 0 0 1 0 0 0 1 0 0 1 0 0 0  1 1 0 0 1 1 0 0 0 0 1 1 1 0 0 1 1 1 0 0 0 0 0 0 0 1 1 0  1 0 1 0 0 0 1 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 0 0 0 0 0 1  1 0 0 1 0 0 1 0 1 0 1 1 1 0 1 0 0 0 0 0 0 0 1 1 1 0 0 1  1 0 0 0 1 0 0 1 1 1 0 1 1 0 0 1 0 0 0 1 0 0 1 0 0 1 0 1  1 0 0 0 0 1 0 1 1 1 1 0 1 0 0 0 1 0 0 0 1 0 0 1 0 0 1 1  1 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 1 0  0 1 1 0 0 0 1 0 1 0 0 0 0 0 1 1 1 1 0 1 1 1 0 0 0 0 0 1  0 1 0 1 0 0 1 0 0 1 0 0 0 1 0 1 1 1 0 0 0 0 1 1 1 0 0 1  0 1 0 0 1 0 0 1 0 0 1 0 0 1 1 0 1 1 0 1 0 0 1 0 0 1 0 1  0 1 0 0 0 1 0 1 0 0 0 1 0 1 1 1 0 1 0 0 1 0 0 1 0 0 1 1  0 1 0 0 0 0 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 1 0 0 1 1 1 0  0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0  0 0 1 0 1 0 0 0 1 0 1 0 0 1 0 1 0 0 1 0 1 1 1 0 0 1 0 1  0 0 1 0 0 1 0 0 1 0 0 1 0 1 0 0 1 0 1 1 0 1 0 1 0 0 1 1  0 0 1 0 0 0 1 0 1 0 0 0 1 1 0 0 0 1 1 1 1 0 0 0 1 1 1 0  0 0 0 1 1 0 0 0 0 1 1 0 0 0 1 1 0 0 1 1 0 0 0 1 1 1 0 1  0 0 0 1 0 1 0 0 0 1 0 1 0 0 1 0 1 0 1 0 1 0 1 0 1 0 1 1  0 0 0 1 0 0 1 0 0 1 0 0 1 0 1 0 0 1 1 0 0 1 1 1 0 1 1 0  0 0 0 0 1 0 0 1 0 0 1 0 1 0 0 1 0 1 1 1 0 1 1 0 1 0 1 0  0 0 0 0 0 1 0 1 0 0 0 1 1 0 0 0 1 1 1 0 1 1 0 1 1 1 0 0  0 0 0 0 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 0 1 1 0 0 0 0'

In [57]:
Chang3 = '0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 1 1 0 1 0 0 0 0 1 0 0 0 0 1 1 1 1 0 0 0 0 0 0 1 1 1 0 1 1 0 1 0 1 0 0 0 0 1 0 0 0 1 1 0 0 1 1 0 0 0 0 1 1 1 1 0 0 1 0 1 0 1 0 0 0 1 1 0 0 1 0 0 0 1 0 1 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 0 0 1 0 0 1 1 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 0 1 0 1 1 0 1 0 1 0 0 0 1 0 0 0 0 1 0 1 1 0 1 0 1 0 0 0 1 0 1 1 0 1 0 1 1 0 0 0 0 0 1 0 0 0 1 1 0 1 0 1 0 1 0 0 0 1 1 1 0 0 0 0 0 1 0 1 1 0 0 1 0 0 1 1 0 0 1 0 1 0 1 0 0 1 1 1 0 0 0 0 0 0 1 0 0 1 1 0 1 1 0 1 0 0 0 1 0 1 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 1 0 1 1 1 0 1 0 0 0 0 1 0 1 1 1 1 0 1 0 0 0 1 0 0 0 1 0 0 0 1 1 0 1 1 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 1 0 1 1 0 0 1 1 0 0 0 0 0 0 0 0 1 1 1 0 1 1 1 0 0 0 1 1 0 0 1 0 1 1 0 0 1 0 0 0 0 0 0 0 1 1 1 1 0 0 0 1 1 1 0 0 1 0 1 0 0 1 0 1 0 0 0 1 0 0 1 1 0 1 1 0 0 0 0 1 0 1 1 1 0 0 1 0 0 0 1 0 1 0 0 0 1 0 1 1 1 0 1 0 0 1 0 0 0 1 1 0 1 0 1 0 0 0 0 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 1 0 1 0 0 1 1 0 0 1 1 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 1 1 1 1 1 0 0 1 0 0 1 1 0 1 0 0 0 1 0 0 0 1 0 0 0 0 1 0 1 1 1 1 0 1 1 0 0 0 1 0 0 1 0 0 1 0 0 1 0 1 0 0 1 0 1 1 0 1 0 0 1 1 0 1 0 0 1 0 0 0 1 0 1 0 0 0 1 1 0 0 0 1 1 1 1 0 0 1 0 0 1 1 0 0 0 1 1 0 0 0 0 1 1 0 0 0 1 1 0 0 1 1 0 0 0 1 1 1 1 0 0 0 0 1 0 0 0 1 0 1 0 0 1 0 1 0 0 1 1 1 0 1 1 0 0 0 1 1 0 0 0 0 1 0 0 0 1 0 1 1 0 0 1 1 1 0 1 0 1 0 1 0 0 1 0 1 0 0 0 0 0 1 0 0 0 1 1 1 0 1 0 1 1 0 0 1 1 0 1 0 1 0 1 0 0 0 0 0 0 0 1 0 0 1 1 0 1 1 0 1 0 1 0 1 0 1 1 1 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 0 1 0 1 1 1 0 1 1 0 1 1 0 0 0'

In [58]:
Chang1 = Chang1.replace('  ', ' ')
Chang2 = Chang2.replace('  ', ' ')
Chang3 = Chang3.replace('  ', ' ')

In [61]:
len(Chang1), len(Chang2), len(Chang3)

(1567, 1567, 1567)

In [67]:
for graph in [Chang1, Chang2, Chang3]:
    graphstring = graph
    graphstring = graphstring.replace(' ', '')
    n, d = len(graphstring), int(np.sqrt(len(graphstring)))

    M = []
    for i in range(d):
        s, row = graphstring[i*d:(i+1)*d], [0]*d
        for j in range(d):
            if s[j]=='1':
                row[j]=1
        M.append(row)

    G = Graph(Matrix(M))
    e, c = lu_spectrum(G,1)
    print("L_1_up spectrum")
    for (ee, cc) in zip(e,c):
        print('[',ee, ',', cc,']', end = ';')
    print()
    print()

L_1_up spectrum
[ 0.0 , 27 ];[ 2.006 , 3 ];[ 2.431 , 10 ];[ 3.694 , 4 ];[ 3.76 , 3 ];[ 4.527 , 5 ];[ 5.382 , 6 ];[ 5.389 , 10 ];[ 5.537 , 5 ];[ 5.623 , 8 ];[ 6.726 , 8 ];[ 6.853 , 3 ];[ 7.618 , 6 ];[ 7.691 , 3 ];[ 8.0 , 8 ];[ 8.52 , 4 ];[ 8.935 , 5 ];[ 9.167 , 3 ];[ 9.359 , 10 ];[ 9.523 , 3 ];[ 9.651 , 8 ];[ 9.786 , 4 ];[ 9.821 , 10 ];[ 10.0 , 12 ];

L_1_up spectrum
[ 0.0 , 27 ];[ 2.188 , 8 ];[ 2.412 , 6 ];[ 2.703 , 3 ];[ 4.501 , 8 ];[ 5.0 , 8 ];[ 5.213 , 3 ];[ 5.438 , 6 ];[ 7.0 , 33 ];[ 7.398 , 6 ];[ 8.0 , 4 ];[ 8.762 , 8 ];[ 9.084 , 3 ];[ 9.19 , 6 ];[ 9.549 , 8 ];[ 9.562 , 6 ];[ 10.0 , 25 ];

L_1_up spectrum
[ 0.0 , 27 ];[ 2.0 , 1 ];[ 2.124 , 3 ];[ 2.271 , 4 ];[ 2.536 , 4 ];[ 3.172 , 1 ];[ 3.648 , 4 ];[ 3.895 , 3 ];[ 4.0 , 1 ];[ 4.438 , 3 ];[ 4.869 , 4 ];[ 5.0 , 2 ];[ 5.18 , 4 ];[ 5.335 , 4 ];[ 5.438 , 5 ];[ 5.559 , 3 ];[ 6.0 , 4 ];[ 6.078 , 4 ];[ 7.0 , 13 ];[ 7.452 , 4 ];[ 7.485 , 3 ];[ 7.648 , 4 ];[ 8.203 , 4 ];[ 8.562 , 3 ];[ 8.828 , 1 ];[ 8.88 , 4 ];[ 9.0 , 3 ];[ 9.258 , 3 ];[ 9.